### ISSUE TITLE
Getting WebSocket is closed before the connection is established in production setup

### ISSUE THREAD

**Issue by dchersey** [rails/actioncable#131]
Hi, my action cable is working just fine on development, but when I configure it for production using an nginx reverse proxy, I get the repeated message in my browser that the webSocket is closed before the connection is established.

I believe my nginx reverse proxy is working properly, as I am getting access.log entries and no error.log entries. When kill my cable server (using puma) the nginx error.log tells me it could not proxy. All the connection info being logged is correct; it is redirecting port 81 to my cable server on localhost. 

```
2015/12/07 15:27:56 [error] 12984#0: *1556 connect() failed (111: Connection refused) while connecting to upstream, client: 171.159.221.134, server: localhost, request: "GET / HTTP/1.1", upstream: "http://0.0.0.0:28080/", host: "ia.scrum-masters.com:81"
```

I have configured nginx to pass along the upgrade headers. 

```
    location / {
        proxy_pass http://cable;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
```

This could be a CORS issue I suppose, but I can't seem to debug it to confirm.  Puma is not logging anything on my cable server (executed using `bundle exec puma -p 28080 cable/config.ru`) as per the README. 

Any help to troubleshoot would be much appreciated!

**Comment by mikecarroll** [comment]
I had a similar issue, did you set the `allowed_request_origins`? It doesn't cause an issue in development mode because it defaults to allowing `localhost` when in development.

I made a pull request with updates to the documentation about this, which has some more detail: https://github.com/rails/actioncable/pull/126

**Comment by dchersey** [comment]
This looks promising; I will play with it. QQ: what should the origin be in the case of an nginx reverse proxy? My server domain name? Localhost on the inbound port (81) ? 

Browser --> NGINX:81 --> AC running on localhost:28080

Thanks!

**Comment by mikecarroll** [comment]
The domain name.

**Comment by dchersey** [comment]
That did the trick!! Many thanks, and :+1:  on this pull request!

For others with this problem reading this, all I did was create an initializer config/cable.rb containing: 
```ruby
ActionCable.server.config.allowed_request_origins = %w( http://my-domain.com  )
```

Now off to layer SSL onto the reverse proxy ...

**Comment by rushingfitness** [comment]
I have a similar issue, but my AC server is set up in app, instead of standalone. I have an initializer that sets the `allowed_request_origins` and can verify it is set if I do a rails console to check the value. However I'm still getting a 404. Is it possible because it's in app and not standalone?

**Comment by mikecarroll** [comment]
@rushingfitness I mounted it in `routes.rb`. I actually raised, and later self-answered, some questions about it on SO: http://stackoverflow.com/questions/32322652/configuring-nginx-to-proxy-thin-and-rails-actioncable

Maybe that would be the more appropriate place for this continuing this conversation, so that we don't clog up the issues board here.

**Comment by dchersey** [comment]
Your SO thread was very helpful to me, and I posted my thoughts there about server separation and SSL proxying

**Comment by dhh** [comment]
Would be great to collect a FAQ and include links to that SO article. If anyone wants to work on that, please open a PR.

**Comment by rushingfitness** [comment]
My issue was actually a combination of Heroku & Cloudflare. Had to buy an ssl cert and point to a subdomain that didn't use CF's proxy. PITA, but now it works perfectly.

**Comment by dhh** [comment]
Would be great if you could write a tutorial based on the issues you hit. I'm sure you're not alone. Thanks!

**Comment by rushingfitness** [comment]
@dhh should I do any tutorial about this issue I also faced: https://github.com/rails/actioncable/pull/124

**Comment by dhh** [comment]
Not sure I fully follow what the issue is there. Assigned to @lifo to take
a look.
