### ISSUE TITLE
Session Access in ActionCable::Connection

### ISSUE THREAD

**Issue by mieko** [rails/actioncable#77]
It'd be really nice if one could access the Rails session in the context of `ActionCable::Connection` to authorize connections.

My base Rails app uses a Session with CookieStore, and stores the user's ID in `session[:user_id]`, along with a few minor auth-related values.  I've had to visit every controller action which manipulates the session and make sure I've also set a signed cookie that I can read in ActionCable processes.  It leads to a lot of duplication of information, and I'm sure to get them out of sync.

I've looked at ActionCable's cookie loading methods to see if there was something that'd be analogous for sessions, but I think someone more familiar with the stack would have to explain how this would work; I've had no success yet.  Any hints toward implementing this feature (even if it lived external to AC) would be appreciated.

**Comment by kroehre** [comment]
:+1:

**Comment by dgsan** [comment]
I'm curious what you mean by things getting out of sync. I use Redis sessions in my app and I pretty much never put anything in them besides the session[:auth]. For actioncable I do `cookies.signed[:auth] = Base64.encode64(auth.to_msgpack)` (where auth is the same as the contents of session[:auth]) and haven't had a problem. There's really nothing to get out of sync since both cookies are always set (and destroyed) in the same single place.  

In my `ActionCable::Connection::Base` as part of the connect logic (inside of connect def) I use:

```ruby
def set_user
  if cookies.signed[:auth]
    msg = Base64.decode64(cookies.signed[:auth])
    auth = MessagePack.unpack(msg)
    if (auth['user'].length > 0)
      user = User.new
      user.auth_hash = OpenStruct.new(auth)
      user.freeze()
      user.readonly!
      return user # ends up as current_user
    end
  end
  reject_unauthorized_connection
end
```
You might notice that the logic there doesn't check for auth['user'] being valid. This is because all my channels `subscribed` defs have logic along the lines of
```
unless current_user.has_clearance? channel_clearance_key
  reject_unauthorized_connection
end
```
hardwired in.

Anyway, I don't think this is perfect by any means, but I have a really hard time seeing them get out of sync. And I'm somewhat okay with it because I like being able to have the everything in my channels immutable anyway.

**Comment by kroehre** [comment]
@dgsan I _think_ what @mieko was saying is that he's concerned about duplicated code and the risk of that code becoming out of sync.

**Comment by alexpeattie** [comment]
@mieko - Since ActionCable has access to the request's cookies, if you're using `CookieStore`, you should be able to grab your session like so :relaxed: :
~~~ruby
session = cookies.encrypted[Rails.application.config.session_options[:key]]
~~~

This seems to work well, but feels like a bit of a hack. `session` isn't a true session object (i.e. instance of `ActionDispatch::Request::Session`) - e.g. it doesn't have indifferent access and methods like `session.id` won't work. And obviously this approach falls over if you're not using `CookieStore`..

I don't know if there's a more elegant way to expose the session?

**Comment by jeremy** [comment]
https://github.com/rails/actioncable/pull/43/files#diff-1ccdf466a84301f357917905629ef692R135

**Comment by alexpeattie** [comment]
@jeremy - :+1:
